name: dotnetgtd
services:
  web:
    platform: "linux/amd64"
    build: .
    image: ${DOCKERHUB_REGISTRY}/dotnetgtd
    environment:
      ConnectionStrings__DefaultConnection: "Data Source=gtd-db;Initial Catalog=GTD;User Id=sa;Password='Pass@123';Trust Server Certificate=True;"
      HashSalt: "Ax4663akaa" # replace with your hash salt here for more security
      AdminPassword: "admin" #replace with your admin password
    ports:
      - 80:8080

  db:
    container_name: gtd-db
    image: mcr.microsoft.com/azure-sql-edge
    restart: always
    volumes: 
        - azure-sql-edge-data:/var/opt/mssql
    environment:
        MSSQL_SA_PASSWORD: "Pass@123"
        ACCEPT_EULA: "Y"
volumes:
    azure-sql-edge-data: