name: Build Docker Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: create .env
      working-directory: ./src
      run: echo "DOCKERHUB_REGISTRY=${{ secrets.DOCKERHUB_REGISTRY }}" > .env
    - name: Build the Docker image
      working-directory: ./src
      run: docker compose build
    - name: Login
      working-directory: ./src
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASS }}
    - name: Push Docker image
      working-directory: src/ 
      run: docker compose push web
